import {
  GENERATED_CODE_LENGTH,
  GENERATED_CODE_PREFIX,
} from "@/constants/productCodes";

/**
 * Computes the EAN-13 check digit for the first 12 digits of a code.
 */
function calculateCheckDigit(base: string): number {
  let sum = 0;
  for (let i = 0; i < base.length; i++) {
    const digit = parseInt(base[i], 10);
    sum += i % 2 === 0 ? digit : digit * 3;
  }
  return (10 - (sum % 10)) % 10;
}

/**
 * Generates a unique EAN-13 barcode for a product.
 *
 * The code is built on the GS1 restricted-circulation prefix (see
 * GENERATED_CODE_PREFIX), which makes it impossible to collide with a real
 * manufacturer barcode while still scanning as a standard EAN-13.
 *
 * Layout: [040][9 random digits][check digit]
 *
 * @param existingCodes codes already taken within the business, to keep uniqueness
 */
function generateEAN13(existingCodes: Set<string>, maxAttempts = 1000): string {
  const randomDigits = GENERATED_CODE_LENGTH - GENERATED_CODE_PREFIX.length - 1;

  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const random = String(
      Math.floor(Math.random() * 10 ** randomDigits)
    ).padStart(randomDigits, "0");
    const base = GENERATED_CODE_PREFIX + random;
    const code = base + calculateCheckDigit(base);

    if (!existingCodes.has(code)) {
      return code;
    }
  }
  throw new Error("No se pudo generar un código único");
}

/**
 * Tells whether a barcode was generated by Cuadre de Caja or belongs to the
 * real product. Relies on the reserved GS1 prefix, so it has no false positives.
 */
export function isGeneratedProductCode(codigo: string): boolean {
  return (
    typeof codigo === "string" &&
    codigo.length === GENERATED_CODE_LENGTH &&
    codigo.startsWith(GENERATED_CODE_PREFIX) &&
    /^\d+$/.test(codigo)
  );
}

export default generateEAN13;
